### ISSUE TITLE
documentation missing rationale or reason for adopting over handlebars-formatter

### ISSUE THREAD

**Issue by brokenalarms** [ember-tooling/prettier-for-handlebars-vscode#13]
I have checked release notes, issues, pull requests and description docs in both github and VSCode marketplace, but I can't find anything that explains why the fork or why this one (with more recent updates) should be the chosen VSCode extension over the other.

At present, I'll use the mfeckie one since it preserves newlines, which is essential for our team's project, but I think the documentation needs to be updated to give the use case for this, otherwise there is nothing making any kind of argument for its use besides whether you want newlines or not.

**Comment by carusog** [comment]
Thanks @brokenalarms 
This issue allowed me to find handlebars-formatter and, substituting it to this fork, I was able to fix a line with variable split into multiple lines. It was super annoying.

**Comment by Alonski** [comment]
@brokenalarms The original reason I created this extension is because `handlebars-formatter` wasn't setup to use .prettierrc originally.
Now it does.

The reason I still use this extension personally is because I pinned Prettier to v1.18.2
There is inconsistent behavior in new version of Prettier:
https://github.com/jgwhite/prettier/issues/1#issuecomment-602504650

**Comment by brokenalarms** [comment]
Thanks @Alonski, that's good to know. Probably worth just adding that to the main page so people can tell at a glance. Thanks!

**Comment by Alonski** [comment]
> Thanks @Alonski, that's good to know. Probably worth just adding that to the main page so people can tell at a glance. Thanks!

Do you have time to open a small PR?

**Comment by Alonski** [comment]
Just updated the README explaining this.
